//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoQuiz.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa.
        /// </summary>
        public static string africa {
            get {
                return ResourceManager.GetString("africa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer options.
        /// </summary>
        public static string answer_options {
            get {
                return ResourceManager.GetString("answer_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer {0}options.
        /// </summary>
        public static string answer_options_br {
            get {
                return ResourceManager.GetString("answer_options_br", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia.
        /// </summary>
        public static string asia {
            get {
                return ResourceManager.GetString("asia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia and Oceania.
        /// </summary>
        public static string australia {
            get {
                return ResourceManager.GetString("australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continents.
        /// </summary>
        public static string continents {
            get {
                return ResourceManager.GetString("continents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answers.
        /// </summary>
        public static string correct {
            get {
                return ResourceManager.GetString("correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answers.
        /// </summary>
        public static string correct_answers {
            get {
                return ResourceManager.GetString("correct_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all.
        /// </summary>
        public static string deselect_all_btn {
            get {
                return ResourceManager.GetString("deselect_all_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string difficulty {
            get {
                return ResourceManager.GetString("difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty{0}&amp;nbsp;.
        /// </summary>
        public static string difficulty_br {
            get {
                return ResourceManager.GetString("difficulty_br", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easy.
        /// </summary>
        public static string difficulty_easy {
            get {
                return ResourceManager.GetString("difficulty_easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hard.
        /// </summary>
        public static string difficulty_hard {
            get {
                return ResourceManager.GetString("difficulty_hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string difficulty_medium {
            get {
                return ResourceManager.GetString("difficulty_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to very hard.
        /// </summary>
        public static string difficulty_very_hard {
            get {
                return ResourceManager.GetString("difficulty_very_hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string distractors_none {
            get {
                return ResourceManager.GetString("distractors_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the capital of.
        /// </summary>
        public static string enter_capital_of {
            get {
                return ResourceManager.GetString("enter_capital_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string europe {
            get {
                return ResourceManager.GetString("europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitals.
        /// </summary>
        public static string game_mode_btn_capitals {
            get {
                return ResourceManager.GetString("game_mode_btn_capitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string game_mode_btn_countries {
            get {
                return ResourceManager.GetString("game_mode_btn_countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string game_mode_btn_flags {
            get {
                return ResourceManager.GetString("game_mode_btn_flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitals game mode.
        /// </summary>
        public static string game_mode_capitals {
            get {
                return ResourceManager.GetString("game_mode_capitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries game mode.
        /// </summary>
        public static string game_mode_countries {
            get {
                return ResourceManager.GetString("game_mode_countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags game mode.
        /// </summary>
        public static string game_mode_flags {
            get {
                return ResourceManager.GetString("game_mode_flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest streak.
        /// </summary>
        public static string longest_streak {
            get {
                return ResourceManager.GetString("longest_streak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You ran out of time!.
        /// </summary>
        public static string mistake_timeout {
            get {
                return ResourceManager.GetString("mistake_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong! Correct answer was.
        /// </summary>
        public static string mistake_wrong_capital {
            get {
                return ResourceManager.GetString("mistake_wrong_capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong! That was flag of.
        /// </summary>
        public static string mistake_wrong_country {
            get {
                return ResourceManager.GetString("mistake_wrong_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong! It was flag of.
        /// </summary>
        public static string mistake_wrong_flag {
            get {
                return ResourceManager.GetString("mistake_wrong_flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure non-sovereign countries.
        /// </summary>
        public static string non_sovereign_btn {
            get {
                return ResourceManager.GetString("non_sovereign_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included non-sovereign countries.
        /// </summary>
        public static string non_sovereign_modal_caption {
            get {
                return ResourceManager.GetString("non_sovereign_modal_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North America.
        /// </summary>
        public static string north_america {
            get {
                return ResourceManager.GetString("north_america", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North and South America.
        /// </summary>
        public static string north_and_south_americas {
            get {
                return ResourceManager.GetString("north_and_south_americas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string question_num {
            get {
                return ResourceManager.GetString("question_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions total.
        /// </summary>
        public static string questions_total {
            get {
                return ResourceManager.GetString("questions_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string results_title {
            get {
                return ResourceManager.GetString("results_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string select_all_btn {
            get {
                return ResourceManager.GetString("select_all_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the capital of.
        /// </summary>
        public static string select_capital_of {
            get {
                return ResourceManager.GetString("select_capital_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What country does this flag belong to?.
        /// </summary>
        public static string select_country_of {
            get {
                return ResourceManager.GetString("select_country_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select flag of.
        /// </summary>
        public static string select_flag_of {
            get {
                return ResourceManager.GetString("select_flag_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South America.
        /// </summary>
        public static string south_america {
            get {
                return ResourceManager.GetString("south_america", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start!.
        /// </summary>
        public static string start_btn {
            get {
                return ResourceManager.GetString("start_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new game.
        /// </summary>
        public static string start_new_game {
            get {
                return ResourceManager.GetString("start_new_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streak.
        /// </summary>
        public static string streak {
            get {
                return ResourceManager.GetString("streak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time left.
        /// </summary>
        public static string time_left {
            get {
                return ResourceManager.GetString("time_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time limit.
        /// </summary>
        public static string time_limit {
            get {
                return ResourceManager.GetString("time_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time {0}limit.
        /// </summary>
        public static string time_limit_br {
            get {
                return ResourceManager.GetString("time_limit_br", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your answer.
        /// </summary>
        public static string type_here_hint {
            get {
                return ResourceManager.GetString("type_here_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited time.
        /// </summary>
        public static string unlimited_time {
            get {
                return ResourceManager.GetString("unlimited_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well done!.
        /// </summary>
        public static string well_done {
            get {
                return ResourceManager.GetString("well_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌍 Whole world.
        /// </summary>
        public static string whole_world {
            get {
                return ResourceManager.GetString("whole_world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong answers.
        /// </summary>
        public static string wrong {
            get {
                return ResourceManager.GetString("wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong answers.
        /// </summary>
        public static string wrong_answers {
            get {
                return ResourceManager.GetString("wrong_answers", resourceCulture);
            }
        }
    }
}
