//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoQuiz.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa.
        /// </summary>
        public static string africa {
            get {
                return ResourceManager.GetString("africa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer options.
        /// </summary>
        public static string answer_options {
            get {
                return ResourceManager.GetString("answer_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia.
        /// </summary>
        public static string asia {
            get {
                return ResourceManager.GetString("asia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia and Oceania.
        /// </summary>
        public static string australia {
            get {
                return ResourceManager.GetString("australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continents.
        /// </summary>
        public static string continents {
            get {
                return ResourceManager.GetString("continents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all.
        /// </summary>
        public static string deselect_all_btn {
            get {
                return ResourceManager.GetString("deselect_all_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string difficulty {
            get {
                return ResourceManager.GetString("difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string europe {
            get {
                return ResourceManager.GetString("europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitals.
        /// </summary>
        public static string game_mode_btn_capitals {
            get {
                return ResourceManager.GetString("game_mode_btn_capitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string game_mode_btn_countries {
            get {
                return ResourceManager.GetString("game_mode_btn_countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string game_mode_btn_flags {
            get {
                return ResourceManager.GetString("game_mode_btn_flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure non-sovereign countries.
        /// </summary>
        public static string non_sovereign_btn {
            get {
                return ResourceManager.GetString("non_sovereign_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included non-sovereign countries.
        /// </summary>
        public static string non_sovereign_modal_caption {
            get {
                return ResourceManager.GetString("non_sovereign_modal_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North America.
        /// </summary>
        public static string north_america {
            get {
                return ResourceManager.GetString("north_america", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string select_all_btn {
            get {
                return ResourceManager.GetString("select_all_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South America.
        /// </summary>
        public static string south_america {
            get {
                return ResourceManager.GetString("south_america", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start!.
        /// </summary>
        public static string start_btn {
            get {
                return ResourceManager.GetString("start_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new game.
        /// </summary>
        public static string start_new_game {
            get {
                return ResourceManager.GetString("start_new_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time limit.
        /// </summary>
        public static string time_limit {
            get {
                return ResourceManager.GetString("time_limit", resourceCulture);
            }
        }
    }
}
